const adminAuth = (req, res, next) => {
    // check if the user is admin or not
    console.log("admin auth is getting checked");
    const token = "xyz"; // this token will be generated by the server and sent to the client after login
    const isAdminAuthorized = token === "xyz" ? true : false;
    if (!isAdminAuthorized) {
        res.status(401).send("Unauthorized request  ");
    } else {
        next();
    };
}
module.exports = { adminAuth };